package:
  name: fklab-python-core
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'develop') }}

source:
  git_url: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11>=2.2
  run:
    - python
    - numpy
    - scipy>=1.2
    - numba
    - h5py
    - matplotlib
    - pyyaml
