package:
  name: fklab-python-core
  version: "1.01"

source:
  git_url: ..

build:
  number: 1

requirements:
  build:
    - setuptools
    - python
    - numpy
    - scipy
    - numba
    - h5py
    - pybind11
    - matplotlib
    - spectrum
  run:
    - python
    - numpy
    - scipy
    - numba
    - h5py
    - pybind11
    - matplotlib
    - spectrum
