package:
  name: fklab-python-core
  version: "1.1.1"

source:
  git_url: ..

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy
    - scipy>=1.2
    - numba
    - h5py
    - pybind11>=2.2
    - matplotlib
  run:
    - python
    - numpy
    - scipy>=1.2
    - numba
    - h5py
    - pybind11>=2.2
    - matplotlib
