package:
  name: fklab-python-core
  version: "1.2.0"

source:
  git_url: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11>=2.2
  run:
    - python
    - numpy==1.16.*
    - scipy>=1.2
    - numba
    - h5py
    - matplotlib==3.0.*
    - pyyaml
