language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install pybind11
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  - python -m unittest discover -s tests
